amp: true
input_channels: 1
patch_size: [128, 128, 128]
bundle_root: './models'
fold: 0
infer: {ckpt_name: $@bundle_root + '/model.pt',
        output_path: $@bundle_root + '/prediction',
        log_output_file: $@bundle_root + '/inference.log'}
resample_to_spacing: [1.5, 1.5, 1.5]
model: "vista3d_segresnet_d"
image_key: "image"
transforms_infer:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: "@image_key"
    image_only: True
  - _target_: EnsureChannelFirstd
    keys: "@image_key"
  - _target_: ScaleIntensityRanged
    a_max: 1053.678477684517
    a_min: -963.8247715525971
    b_max: 1.0
    b_min: 0.0
    clip: true
    keys: '@image_key'
  - _target_: Orientationd
    keys: "@image_key"
    axcodes: RAS
  - _target_: Spacingd
    keys: ["@image_key"]
    pixdim: "@resample_to_spacing"
    mode: [bilinear]
    align_corners: [true]
  - _target_: CastToTyped
    keys: "@image_key"
    dtype: "$torch.float32"
