name: premerge-min

on:
  # quick tests for pull requests and the releasing branches
  push:
    branches:
      - vista3d
      - main
  pull_request:

concurrency:
  # automatically cancel the previously triggered workflows when there's a newer version
  group: py-min-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  min-dep-py3:  # min dependencies installed tests for different python
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Prepare pip wheel
      run: |
        which python
        python -m pip install --user --upgrade pip setuptools wheel
    - name: cache weekly timestamp
      id: pip-cache
      run: |
        echo "datew=$(date '+%Y-%V')" >> $GITHUB_OUTPUT
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      shell: bash
    - name: cache for pip
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ubuntu-latest-latest-pip-${{ steps.pip-cache.outputs.datew }}
    - name: Install the dependencies
      run: |
        python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
        python -m pip install "monai[all]"
        python -m pip list
      shell: bash
    - name: Run quick tests (CPU ${{ runner.os }})
      run: |
        python -c 'import torch; print(torch.__version__); print(torch.rand(5,3))'
        python -c "import monai; monai.config.print_config()"
        python -m unittest -v
